<?php $customer = $this->getLoadedCustomer(); ?>
<?php $flags = $this->getFlag(); ?>
<form class="form-horizontal" method="post">
    <div class="control-group <?php echo !empty($customer['nameError'])?'error':'';?>">
        <label class="control-label">Name</label>
        <div class="controls">
            <input name="name" type="text"  placeholder="Name" value="<?php echo !empty($customer['name'])?$customer['name']:'';?>">
            <?php if (!empty($customer['nameError'])): ?>
                <span class="help-inline"><?php echo $customer['nameError'];?></span>
            <?php endif; ?>
        </div>
    </div>
    <div class="control-group <?php echo !empty($customer['emailError'])?'error':'';?>">
        <label class="control-label">Email Address</label>
        <div class="controls">
            <input name="email" type="text" placeholder="Email Address" value="<?php echo !empty($customer['email'])?$customer['email']:'';?>">
            <?php if (!empty($customer['emailError'])): ?>
                <span class="help-inline"><?php echo $customer['emailError'];?></span>
            <?php endif;?>
        </div>
    </div>
    <div class="control-group <?php echo !empty($customer['mobileError'])?'error':'';?>">
        <label class="control-label">Mobile Number</label>
        <div class="controls">
            <input name="mobile" type="text"  placeholder="Mobile Number" value="<?php echo !empty($customer['mobile'])?$customer['mobile']:'';?>">
            <?php if (!empty($customer['mobileError'])): ?>
                <span class="help-inline"><?php echo $customer['mobileError'];?></span>
            <?php endif;?>
        </div>
    </div>
    <?php $this->getChildHtml('button'); ?>
</form>