<!DOCTYPE html>
<html lang="en">
<?php $this->getChildHtml('header'); ?>

<body>
<div class="container">
    <div class="row">
        <h3>My Contact List</h3>
    </div>
    <div class="row">
        <p>
            <a href="contact/customer/create/" class="btn btn-success">Create</a>
        </p>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Email Address</th>
                <th>Mobile Number</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div> <!-- /container -->
</body>
</html>
