<!DOCTYPE html>
<html lang="en">
<?php $this->getChildHtml('header'); ?>

<body>
<div class="container">
    <div class="row">
        <h3>My Contact List</h3>
    </div>
    <div class="row">
        <p>
            <a href="contact/customer/create/" class="btn btn-success">Create</a>
        </p>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Email Address</th>
                <th>Mobile Number</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $customers = $this->getAllLoadedCustomers();
            foreach($customers as $customer) {
                echo '<tr>';
                echo '<td>' . $customer['name'] . '</td>';
                echo '<td>' . $customer['email'] . '</td>';
                echo '<td>' . $customer['mobile'] . '</td>';
                echo '<td width=250>';
                echo '<a class="btn" href="/contact/customer/read/'.$customer['id'].'">Read</a>';
                echo ' ';
                echo '<a class="btn btn-success" href="/contact/customer/update/'.$customer['id'].'">Update</a>';
                echo ' ';
                echo '<a class="btn btn-danger" href="/contact/customer/delete/'.$customer['id'].'">Delete</a>';
                echo '</td>';
                echo '</tr>'; }
            ?>
            </tbody>
        </table>
    </div>
</div> <!-- /container -->
</body>
</html>
