<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,800,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700' rel='stylesheet' type='text/css'>
<!--    <link rel="icon" type="image/png" href="http://fc09.deviantart.net/fs71/i/2010/141/8/f/Skull_icon_by_Sergioelmoreno.png">-->
    <link rel="icon" type="image/png" href="http://73425.inspyred.com/images/booklet%20read.png">
    <link href="<?php echo DS . 'assets' . DS . 'dist' . DS . 'css' . DS . 'bootstrap.css'?>" rel="stylesheet">
    <link href="<?php echo DS . 'assets' . DS . 'dist' . DS . 'css' . DS . 'cover.css'?>" rel="stylesheet">
    <link href="<?php echo DS . 'assets' . DS . 'bootstrap-social-gh-pages' . DS . 'bootstrap-social.css'?>" rel="stylesheet">
</head>

test