<!DOCTYPE html>
<html lang="en">
<?php $this->getChildHtml('header'); ?>

<body>
   <?php $this->getChildHtml('content'); ?>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="<?php echo DS . 'assets' . DS . 'dist' . DS . 'js' . DS . 'bootstrap.min.js'?>"></script>
<script>
    $('.login-btn').click(function(){
        FB.login(function(response) {
            if (response.status === 'connected') {
                console.log(response);
            } else if (response.status === 'not_authorized') {
                // The person is logged into Facebook, but not your app.
            } else {
                // The person is not logged into Facebook, so we're not sure if
                // they are logged into this app or not.
            }
        });
    })
</script>
</html>