<div class="site-wrapper cover-bg">

    <div class="site-wrapper-inner">

        <div class="cover-container">
            <div class="inner cover">
                <h1 class="cover-heading">Dark Baggage</h1>

                <div class="row">
                    <div class="form-cover col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4 col-md-6 col-md-offset-3">

                        <p class="lead">
                            <a href="/dark-baggage/register" class="btn btn-lg btn-block btn-fb">Register with Facebook</a>
                        </p>

                        <p class="lead">
                            <a href="#" class="btn btn-lg btn-block btn-email">Register with Email</a>
                        </p>

                        <p class="lead">
                            <a href="#" class="btn btn-lg btn-block btn-email">Log In</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="mastfoot">
                <div class="inner">
                    <p>Designed and developed at <a href="http://www.blueacorn.com/">Blue Acorn</a>, by <a href="https://twitter.com/jpsi5">Justin Simon</a>.</p>
                </div>
            </div>

        </div>

    </div>

</div>