<?php $imageUrl = $this->getFbImageUrl(); ?>

<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">

            <?php $this->getChildHtml('navbar'); ?>

            <div class="inner cover">
               <div class="row">
                   <div class="col-xs-10 col-xs-offset-1">
                       <img class="img-circle fa-img-border" src="<?php echo $imageUrl; ?>" alt="">
                   </div>
               </div>
                <div class="row stats">
                    <div class="col-xs-4 stats-border-bottom stats-container">
                        <p class="stats-title">Connections</p>
                        <p class="">33</p>
                    </div>
                    <div class="col-xs-4 stats-border-bottom stats-border-left stats-container">
                        <p class="stats-title">Confirmed</p>
                        <p class="">14</p>
                    </div>
                    <div class="col-xs-4 stats-border-bottom stats-border-left stats-container">
                        <p class="stats-title">Suspect</p>
                        <p class="">16</p>
                    </div>
                </div>
            </div>

            <div class="mastfoot">
                <div class="inner">
                    <p>Designed and developed at <a href="http://www.blueacorn.com/">Blue Acorn</a>, by <a href="https://twitter.com/jpsi5">Justin Simon</a>.</p>                </div>
            </div>

        </div>

    </div>

</div>