<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">

            <?php $this->getChildHtml('navbar'); ?>

            <div class="inner cover">
               <div class="row">
                   <div class="col-xs-10 col-xs-offset-1">
                       <img class="img-circle " src="" alt="">
                   </div>
                   <div class="col-xs-10 col-xs-offset-1">
                       <h3 class="profile-name"></h3>
                   </div>
                   <div class="col-xs-10 col-xs-offset-1">
                       <p class="stats-title"></p>
                   </div>
               </div>
                <div class="row stats">
                    <div class="col-xs-4 stats-container">
                        <p class="stats-value">33</p>
                        <p class="stats-title">Connections</p>
                    </div>
                    <div class="col-xs-4 stats-border-left stats-container">
                        <p class="stats-value">14</p>
                        <p class="stats-title">Confirmed</p>
                    </div>
                    <div class="col-xs-4 stats-border-left stats-container">
                        <p class="stats-value">8</p>
                        <p class="stats-title">Suspect</p>
                    </div>
                </div>
            </div>

            <div class="mastfoot">
                <div class="inner">
                    <p>Designed and developed at <a href="http://www.blueacorn.com/">Blue Acorn</a>, by <a href="https://twitter.com/jpsi5">Justin Simon</a>.</p>                </div>
            </div>

        </div>

    </div>

</div>

<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : <?php echo APP_ID; ?>,
            xfbml      : true,
            version    : 'v2.1'
        });

        FB.login(function(response) {
            // Original FB.login code
        }, { auth_type: 'reauthenticate' })
    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>