<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">

            <?php $this->getChildHtml('navbar'); ?>

            <div class="inner cover">
               <div class="row">
                   <div class="col-xs-10 col-xs-offset-1">
<!--                       <img src="">-->
                   </div>
               </div>
            </div>

            <div class="mastfoot">
                <div class="inner">
                    <p>Designed and developed at <a href="http://www.blueacorn.com/">Blue Acorn</a>, by <a href="https://twitter.com/jpsi5">Justin Simon</a>.</p>                </div>
            </div>

        </div>

    </div>

</div>