<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Walter+Turncoat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
    <link href="<?php echo DS . 'assets' . DS . 'dist' . DS . 'css' . DS . 'bootstrap.css'?>" rel="stylesheet">
    <link href="<?php echo DS . 'assets' . DS . 'dist' . DS . 'css' . DS . 'cover.css'?>" rel="stylesheet">
    <link href="<?php echo DS . 'assets' . DS . 'bootstrap-social-gh-pages' . DS . 'bootstrap-social.css'?>" rel="stylesheet">
</head>